### PR TITLE
added squawk code description lookup, fonts are now loaded protocol d…

### PR DESCRIPTION
**Pull request by saschaludwig**
I added squawk code description lookup, fonts are now loaded protocol dependent.

I added a squawk.json file with all squawk code descriptions I had available here.
This data is being loaded on page initialisation and informations are displayed in the infoblock.
The location of the squawk code description is just an example.

Because I use dump1090 through a ssl connection I changed the url for the fonts to // instead of http:// to prevent mixed contents (http/https) in the page.

Please edit as needed.

### CODE REVIEW

**Comment by saschaludwig** [comment]
Most of the codes are similar to http://www.flightradars.eu/squawkcodes.html, I added some manually from germany and switzerland. Some are missing. It would be much appreciated if you know of a better/reliable source, maybe grouped by country so one could use the local list. So this list is faulty and not complete :-/

**Comment by tedsluis** [comment]
Nice idea. I have tried it, but I think it does not work?!
I have cloned your repo and build a fresh dump1090.
Whatever plane I select, the Squawk description always displays n/a. Even when the Squawk code is in the database. Look in the picture below where the Squawk code is 1000 and the description is n/a:
image
What could be wrong?

**Comment by saschaludwig** [comment]
Hi

Is the squawk.json file in the html dir?
If I got it right the debian/dump1090-mutability.install should handle the copy to /usr/share/dump1090…

Can you take a look at your browsers network activity? is the file beeing loaded?
You could also test to access squawks['1000‘] from the js console of your browser.

Otherwise I don’t have a clue what has gone wrong.

Please keep in mind that the supplied squawk.json file is not complete nor does the info in there apply for the whole world.
Those codes may vary from country to country :-(
But that is the best I got at the moment ;-)

Best regards, Sascha

**Comment by tedsluis** [comment]
I tried valid codes that are present in the squawk.json. 
squawk.json is in the /usr/share/dump1090-mutability/html dir, but it is not loaded in the browsers network activity. I checked and all your commits are present.

**Comment by saschaludwig** [comment]
Could it be that your browser cached the old js file?

**Comment by tedsluis** [comment]
Your right, that was the case!
Thanks a lot!

**Pull request merged**
